// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetV1ExecutionsByIdData, GetV1ExecutionsByIdResponses, GetV1MeData, GetV1MeErrors, GetV1MeResponses, GetV1NiraConversationsByIdData, GetV1NiraConversationsByIdMessagesData, GetV1NiraConversationsByIdMessagesResponses, GetV1NiraConversationsByIdResponses, GetV1PlaybooksData, GetV1PlaybooksResponses, GetV1WorkspacesData, GetV1WorkspacesErrors, GetV1WorkspacesResponses, PostV1NiraConversationsByIdMessagesData, PostV1NiraConversationsByIdMessagesResponses, PostV1NiraConversationsData, PostV1NiraConversationsResponses, PostV1PlaybooksByPlaybookIdExecuteData, PostV1PlaybooksByPlaybookIdExecuteResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Get current user
 *
 * Returns the authenticated user profile, organization, and available workspaces. Requires Clerk JWT authentication (not API key).
 */
export const getV1Me = <ThrowOnError extends boolean = false>(options?: Options<GetV1MeData, ThrowOnError>) => (options?.client ?? client).get<GetV1MeResponses, GetV1MeErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/me',
    ...options
});

/**
 * List workspaces
 *
 * Returns workspaces accessible to the authenticated user. Requires Clerk JWT authentication (not API key).
 */
export const getV1Workspaces = <ThrowOnError extends boolean = false>(options?: Options<GetV1WorkspacesData, ThrowOnError>) => (options?.client ?? client).get<GetV1WorkspacesResponses, GetV1WorkspacesErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/workspaces',
    ...options
});

/**
 * List playbooks
 *
 * Get a list of all playbooks available in your workspace
 */
export const getV1Playbooks = <ThrowOnError extends boolean = false>(options?: Options<GetV1PlaybooksData, ThrowOnError>) => (options?.client ?? client).get<GetV1PlaybooksResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/playbooks',
    ...options
});

/**
 * Execute playbook
 *
 * Execute a playbook with optional parameters
 */
export const postV1PlaybooksByPlaybookIdExecute = <ThrowOnError extends boolean = false>(options: Options<PostV1PlaybooksByPlaybookIdExecuteData, ThrowOnError>) => (options.client ?? client).post<PostV1PlaybooksByPlaybookIdExecuteResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/playbooks/{playbookId}/execute',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get execution status
 *
 * Poll execution status and retrieve results. Use the ID returned from POST /v1/playbooks/:id/execute
 */
export const getV1ExecutionsById = <ThrowOnError extends boolean = false>(options: Options<GetV1ExecutionsByIdData, ThrowOnError>) => (options.client ?? client).get<GetV1ExecutionsByIdResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/executions/{id}',
    ...options
});

/**
 * Create conversation
 *
 * Create a new conversation with Nira. Optionally provide context for personalization.
 */
export const postV1NiraConversations = <ThrowOnError extends boolean = false>(options?: Options<PostV1NiraConversationsData, ThrowOnError>) => (options?.client ?? client).post<PostV1NiraConversationsResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/nira/conversations',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * Get conversation
 *
 * Get details of a specific conversation
 */
export const getV1NiraConversationsById = <ThrowOnError extends boolean = false>(options: Options<GetV1NiraConversationsByIdData, ThrowOnError>) => (options.client ?? client).get<GetV1NiraConversationsByIdResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/nira/conversations/{id}',
    ...options
});

/**
 * List messages
 *
 * Get messages in a conversation with pagination
 */
export const getV1NiraConversationsByIdMessages = <ThrowOnError extends boolean = false>(options: Options<GetV1NiraConversationsByIdMessagesData, ThrowOnError>) => (options.client ?? client).get<GetV1NiraConversationsByIdMessagesResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/nira/conversations/{id}/messages',
    ...options
});

/**
 * Send message
 *
 * Send a message to Nira. Response is streamed via Server-Sent Events (SSE).
 */
export const postV1NiraConversationsByIdMessages = <ThrowOnError extends boolean = false>(options: Options<PostV1NiraConversationsByIdMessagesData, ThrowOnError>) => (options.client ?? client).sse.post<PostV1NiraConversationsByIdMessagesResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/nira/conversations/{id}/messages',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
