// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetV1AgentsByAgentIdConversationsByConversationIdData, GetV1AgentsByAgentIdConversationsByConversationIdMessagesData, GetV1AgentsByAgentIdConversationsByConversationIdMessagesResponses, GetV1AgentsByAgentIdConversationsByConversationIdResponses, GetV1AgentsData, GetV1AgentsErrors, GetV1AgentsResponses, GetV1ExecutionsByIdData, GetV1ExecutionsByIdResponses, GetV1PlaybooksData, GetV1PlaybooksResponses, PostV1AgentsByAgentIdConversationsByConversationIdMessagesData, PostV1AgentsByAgentIdConversationsByConversationIdMessagesResponses, PostV1AgentsByAgentIdConversationsData, PostV1AgentsByAgentIdConversationsResponses, PostV1PlaybooksByPlaybookIdExecuteData, PostV1PlaybooksByPlaybookIdExecuteResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * List agents
 *
 * Get a list of all agents available in your workspace
 */
export const getV1Agents = <ThrowOnError extends boolean = false>(options?: Options<GetV1AgentsData, ThrowOnError>) => (options?.client ?? client).get<GetV1AgentsResponses, GetV1AgentsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/agents',
    ...options
});

/**
 * List playbooks
 *
 * Get a list of all playbooks available in your workspace
 */
export const getV1Playbooks = <ThrowOnError extends boolean = false>(options?: Options<GetV1PlaybooksData, ThrowOnError>) => (options?.client ?? client).get<GetV1PlaybooksResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/playbooks',
    ...options
});

/**
 * Create conversation with agent
 *
 * Start a new conversation with a specific agent
 */
export const postV1AgentsByAgentIdConversations = <ThrowOnError extends boolean = false>(options: Options<PostV1AgentsByAgentIdConversationsData, ThrowOnError>) => (options.client ?? client).post<PostV1AgentsByAgentIdConversationsResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/agents/{agentId}/conversations',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get conversation
 *
 * Get details of a specific conversation with an agent
 */
export const getV1AgentsByAgentIdConversationsByConversationId = <ThrowOnError extends boolean = false>(options: Options<GetV1AgentsByAgentIdConversationsByConversationIdData, ThrowOnError>) => (options.client ?? client).get<GetV1AgentsByAgentIdConversationsByConversationIdResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/agents/{agentId}/conversations/{conversationId}',
    ...options
});

/**
 * List messages
 *
 * Get messages in a conversation with an agent
 */
export const getV1AgentsByAgentIdConversationsByConversationIdMessages = <ThrowOnError extends boolean = false>(options: Options<GetV1AgentsByAgentIdConversationsByConversationIdMessagesData, ThrowOnError>) => (options.client ?? client).get<GetV1AgentsByAgentIdConversationsByConversationIdMessagesResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/agents/{agentId}/conversations/{conversationId}/messages',
    ...options
});

/**
 * Send message
 *
 * Send a message to a conversation with an agent. Agent response will be generated asynchronously.
 */
export const postV1AgentsByAgentIdConversationsByConversationIdMessages = <ThrowOnError extends boolean = false>(options: Options<PostV1AgentsByAgentIdConversationsByConversationIdMessagesData, ThrowOnError>) => (options.client ?? client).post<PostV1AgentsByAgentIdConversationsByConversationIdMessagesResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/agents/{agentId}/conversations/{conversationId}/messages',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Execute playbook
 *
 * Execute a playbook with optional parameters
 */
export const postV1PlaybooksByPlaybookIdExecute = <ThrowOnError extends boolean = false>(options: Options<PostV1PlaybooksByPlaybookIdExecuteData, ThrowOnError>) => (options.client ?? client).post<PostV1PlaybooksByPlaybookIdExecuteResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/playbooks/{playbookId}/execute',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get execution status
 *
 * Poll execution status and retrieve results. Use the ID returned from POST /v1/playbooks/:id/execute
 */
export const getV1ExecutionsById = <ThrowOnError extends boolean = false>(options: Options<GetV1ExecutionsByIdData, ThrowOnError>) => (options.client ?? client).get<GetV1ExecutionsByIdResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/executions/{id}',
    ...options
});
