// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:3000' | (string & {});
};

export type GetV1AgentsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/agents';
};

export type GetV1AgentsErrors = {
    /**
     * Unauthorized - Invalid or missing API key
     */
    401: {
        error?: string;
        message?: string;
    };
    /**
     * Forbidden - Insufficient permissions
     */
    403: {
        error?: string;
        message?: string;
    };
};

export type GetV1AgentsError = GetV1AgentsErrors[keyof GetV1AgentsErrors];

export type GetV1AgentsResponses = {
    /**
     * List of agents
     */
    200: {
        agents?: Array<{
            id?: string;
            name?: string;
            type?: 'custom' | 'nira' | 'system';
            description?: string;
            createdAt?: string;
            updatedAt?: string;
        }>;
        total?: number;
    };
};

export type GetV1AgentsResponse = GetV1AgentsResponses[keyof GetV1AgentsResponses];

export type GetV1PlaybooksData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/playbooks';
};

export type GetV1PlaybooksResponses = {
    /**
     * List of playbooks
     */
    200: {
        playbooks?: Array<{
            id?: string;
            name?: string;
            description?: string;
            createdAt?: string;
            updatedAt?: string;
        }>;
        total?: number;
    };
};

export type GetV1PlaybooksResponse = GetV1PlaybooksResponses[keyof GetV1PlaybooksResponses];

export type PostV1AgentsByAgentIdConversationsData = {
    body?: {
        title?: string;
        context?: 'sidebar' | 'dedicated';
    };
    path: {
        agentId: string;
    };
    query?: never;
    url: '/v1/agents/{agentId}/conversations';
};

export type PostV1AgentsByAgentIdConversationsResponses = {
    /**
     * Conversation created
     */
    201: {
        id?: string;
        title?: string;
        context?: string;
        status?: string;
        createdAt?: string;
    };
};

export type PostV1AgentsByAgentIdConversationsResponse = PostV1AgentsByAgentIdConversationsResponses[keyof PostV1AgentsByAgentIdConversationsResponses];

export type GetV1AgentsByAgentIdConversationsByConversationIdData = {
    body?: never;
    path: {
        /**
         * Agent ID
         */
        agentId: string;
        /**
         * Conversation ID
         */
        conversationId: string;
    };
    query?: never;
    url: '/v1/agents/{agentId}/conversations/{conversationId}';
};

export type GetV1AgentsByAgentIdConversationsByConversationIdResponses = {
    /**
     * Conversation details
     */
    200: {
        id?: string;
        title?: string;
        context?: string;
        status?: string;
        messageCount?: number;
        lastMessageAt?: string;
        createdAt?: string;
    };
};

export type GetV1AgentsByAgentIdConversationsByConversationIdResponse = GetV1AgentsByAgentIdConversationsByConversationIdResponses[keyof GetV1AgentsByAgentIdConversationsByConversationIdResponses];

export type GetV1AgentsByAgentIdConversationsByConversationIdMessagesData = {
    body?: never;
    path: {
        /**
         * Agent ID
         */
        agentId: string;
        /**
         * Conversation ID
         */
        conversationId: string;
    };
    query?: {
        limit?: number;
        offset?: number;
    };
    url: '/v1/agents/{agentId}/conversations/{conversationId}/messages';
};

export type GetV1AgentsByAgentIdConversationsByConversationIdMessagesResponses = {
    /**
     * List of messages
     */
    200: {
        messages?: Array<{
            id?: string;
            role?: 'user' | 'assistant' | 'system';
            content?: string;
            createdAt?: string;
        }>;
        total?: number;
    };
};

export type GetV1AgentsByAgentIdConversationsByConversationIdMessagesResponse = GetV1AgentsByAgentIdConversationsByConversationIdMessagesResponses[keyof GetV1AgentsByAgentIdConversationsByConversationIdMessagesResponses];

export type PostV1AgentsByAgentIdConversationsByConversationIdMessagesData = {
    body: {
        /**
         * Message content
         */
        content: string;
        role?: 'user' | 'assistant';
        /**
         * Enable streaming mode (alternative to Accept header)
         */
        stream?: boolean;
        /**
         * Enable async mode (return immediately, poll for result)
         */
        async?: boolean;
    };
    path: {
        /**
         * Agent ID
         */
        agentId: string;
        /**
         * Conversation ID
         */
        conversationId: string;
    };
    query?: never;
    url: '/v1/agents/{agentId}/conversations/{conversationId}/messages';
};

export type PostV1AgentsByAgentIdConversationsByConversationIdMessagesResponses = {
    /**
     * Synchronous response - full message
     */
    200: {
        messageId?: string;
        content?: string;
        role?: string;
        executionId?: string;
        tokensUsed?: number;
    };
    /**
     * Async mode - message queued
     */
    202: {
        messageId?: string;
        executionId?: string;
        status?: string;
        message?: string;
    };
};

export type PostV1AgentsByAgentIdConversationsByConversationIdMessagesResponse = PostV1AgentsByAgentIdConversationsByConversationIdMessagesResponses[keyof PostV1AgentsByAgentIdConversationsByConversationIdMessagesResponses];

export type PostV1PlaybooksByPlaybookIdExecuteData = {
    body?: {
        parameters?: {
            [key: string]: unknown;
        };
        priority?: 'high' | 'normal' | 'low';
    };
    path: {
        playbookId: string;
    };
    query?: never;
    url: '/v1/playbooks/{playbookId}/execute';
};

export type PostV1PlaybooksByPlaybookIdExecuteResponses = {
    /**
     * Execution queued - use the returned ID to poll status at GET /v1/executions/:id
     */
    202: {
        /**
         * Execution ID - use this to poll status
         */
        id?: string;
        /**
         * Current execution status
         */
        status?: 'queued';
        message?: string;
    };
};

export type PostV1PlaybooksByPlaybookIdExecuteResponse = PostV1PlaybooksByPlaybookIdExecuteResponses[keyof PostV1PlaybooksByPlaybookIdExecuteResponses];

export type GetV1ExecutionsByIdData = {
    body?: never;
    path: {
        /**
         * Execution ID from the execute response
         */
        id: string;
    };
    query?: never;
    url: '/v1/executions/{id}';
};

export type GetV1ExecutionsByIdResponses = {
    /**
     * Execution details
     */
    200: {
        /**
         * Execution ID
         */
        id?: string;
        /**
         * Current execution status
         */
        status?: 'queued' | 'pending' | 'running' | 'completed' | 'completed_with_errors' | 'failed' | 'cancelled';
        /**
         * Type of target being executed
         */
        targetType?: 'playbook' | 'agent';
        /**
         * ID of the playbook or agent
         */
        targetId?: string;
        /**
         * Name of the playbook or agent
         */
        targetName?: string;
        /**
         * Execution result (available when completed) - can be a string, structured object, or null
         */
        result?: string | {
            [key: string]: unknown;
        } | null;
        /**
         * When execution started
         */
        startedAt?: string;
        /**
         * When execution completed
         */
        completedAt?: string;
        /**
         * Execution duration in milliseconds
         */
        durationMs?: number;
    };
};

export type GetV1ExecutionsByIdResponse = GetV1ExecutionsByIdResponses[keyof GetV1ExecutionsByIdResponses];
